name: Test

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
      - name: Run RuboCop
        run: |
          bundle install
          bundle exec rubocop

  test:
    needs: lint
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-14, windows-latest]
        mruby-version: [master, 3.4.0]
    runs-on: ${{ matrix.runs-on }}
    env:
      MRUBY_VERSION: ${{ matrix.mruby-version}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
      - name: Run build and tests
        run: rake all test

      - name: Memory Leak Check
        if: matrix.runs-on == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y valgrind
          rake test:memcheck

  check:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Check matrix results
        run: |
          if [ "${{ needs.test.result }}" != "success" ]; then
            echo "Some matrix jobs failed"
            exit 1
          fi
      - name: All test matrix jobs completed
        run: echo "All test matrix jobs completed."
